# Radical Cobblemon Trainers — Server Config
# https://srcmc.gitlab.io/rct/docs/0.13/configuration/server_config/

globalSpawnChance = 0.35
globalSpawnChanceMinimum = 0.10
spawnIntervalTicks = 400
spawnIntervalTicksMaximum = 1200
minHorizontalDistanceToPlayers = 24
maxHorizontalDistanceToPlayers = 48
maxVerticalDistanceToPlayers = 24
maxTrainersPerPlayer = 4
maxTrainersTotal = 20
maxLevelDiff = 25
dimensionBlacklist = []
dimensionWhitelist = []
biomeTagBlacklist = []
biomeTagWhitelist = []
initialLevelCap = 15
additiveLevelCapRequirement = 0
allowOverLeveling = false
logSpawning = false
